// 'use client' removed to keep this as a Server Component
import { Geist, Geist_Mono } from "next/font/google";
import ApolloClientWrapper from "../components/ApolloClientWrapper";
import { Toaster } from "sonner";


import "../styles/globals.css";
import "../styles/chips.css";
import "../styles/textFormattingStyles.css"
import { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ApolloClientWrapper>
          {children}
          <Toaster richColors position="top-right" /> 
        </ApolloClientWrapper>
      </body>
    </html>
  );
}
